name: Build Flutter APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: Inject Custom Configs
        run: |
          sed -i 's/applicationId\s*=\s*".*"/applicationId = "com.zouk.hikari.app"/g' android/app/build.gradle.kts
          sed -i 's/signingConfig = signingConfigs.getByName("debug")/signingConfig = signingConfigs.create("release") { storeFile = file("my-release-key.jks"); storePassword = "${{ secrets.KEYSTORE_PASSWORD }}"; keyAlias = "${{ secrets.KEY_ALIAS }}"; keyPassword = "${{ secrets.KEY_PASSWORD }}" }/g' android/app/build.gradle.kts

      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: "build/app/outputs/flutter-apk/app-*-release.apk"
